app:
  inject:
    enabled: true


inject-person-yml:
  person-yml:
    -
      first-name: "????"
      last-name: "???????"
      age: "19"
    -
      first-name: "????"
      last-name: "??????"
      age: "18"
    -
      first-name: "???????"
      last-name: "????????"
      age: "19"
    -
      first-name: "????"
      last-name: "?????????"
      age: "21"
    -
      first-name: "?????"
      last-name: "???????"
      age: "22"
    -
      first-name: "????????"
      last-name: "??????"
      age: "18"