app:
  inject:
    enabled: true

inject-student-yml:
  student-yml:
    -
      first-name: "Анна"
      last-name: "Угрюмченко"
      age: "18"
    -
      first-name: "Евгений"
      last-name: "Бажин"
      age: "20"
    -
      first-name: "Александр"
      last-name: "Казаков"
      age: "21"
    -
      first-name: "Иван"
      last-name: "Новоселов"
      age: "22"
    -
      first-name: "Александр"
      last-name: "Круткин"
      age: "19"
    -
      first-name: "Сергей"
      last-name: "Шестаков"
      age: "21"